project:
  type: website
  output-dir: docs

website:
  title: "Liz Peterson"
  favicon: images/my-favicon.jpg
  navbar:
    title: false
    #logo: images/my-logo.jpg
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
     # - text: CV
     #   href: CV/my-cv.pdf
  page-footer: 
    background: light
    left: Copyright 2024, Elizabeth Peterson
    right: This website is built with {{< fa brands github title="the octocat github icon" >}}

format:
  html:
    theme: styles.scss
    mainfont: Merriweather
    toc: false
    page-layout: full

