---
title: "Resources"
---

## My Links

Here are a few places you can find me online:

- [GitHub](https://github.com/egp4aq) – projects, notebooks, and experiments
- [LinkedIn](https://www.linkedin.com/in/elizabeth-peterson-85046b204/) – let’s connect professionally

- [Goodreads](https://www.goodreads.com/user/show/159610476-liz-peterson) – what I’ve been reading
- [Letterboxd](https://letterboxd.com/yeetlizpete/) – what I’ve been watching

---

## Things I'm Reading & Thinking About

This section is a space where I’ll occasionally share:
Articles I found insightful; Papers or reports I’m engaging with; Tools, podcasts, or resources related to climate, equity, data, or storytelling

Here are a few recent things I’ve found meaningful:

- [Restarting Sable’s Pipeline Would Harm Our Communities, Environment, and Economy](https://www.independent.com/2025/04/25/restarting-sables-pipeline-would-harm-our-communities-environment-and-economy/) - article that features my group's capstone research to advocate for clean energy in SB

---

> _“You do not have to be good. You do not have to walk on your knees for a hundred miles through the desert, repenting. You only have to let the soft animal of your body love what it loves. Tell me about despair, yours, and I will tell you mine. Meanwhile the world goes on. Meanwhile the sun and the clear pebbles of the rain are moving across the landscapes, over the prairies and the deep trees, the mountains and the rivers. Meanwhile the wild geese, high in the clean blue air, are heading home again. Whoever you are, no matter how lonely, the world offers itself to your imagination, calls to you like the wild geese, harsh and exciting– over and over announcing your place in the family of things.” – Mary Oliver_

---

_This space will grow and evolve as I do. Check back for more soon!_
